services:

  openchat-ollama-service:
    image: ollama/ollama:rocm@sha256:4a559b2dd3ef125d83f0b65f3f48d4795569c47d9ddbc3de36b3c1532da194d8
    pull_policy: always
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - app_network
    devices:
      - /dev/kfd
      - /dev/dri
  
  openchat-t2t-service:
    image: opengpunetwork/openchat-text2text:latest@sha256:daf5714a1f8f2b9031d9ed62ffb4cd3763e5ff2bf1063cb58f7b5d90362e4c5e
    pull_policy: always
    ports:
      - "${PORT}:5555"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CALLBACK_URL=${CALLBACK_URL}
      - OLLAMA_HOST=http://openchat-ollama-service:11434
    depends_on:
      - openchat-ollama-service
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  ollama_models:
    driver: local